version: "0.5"

processes:
  server:
    command: cargo watch -x 'loco start' -w src -w config -w assets/views
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 5150
        path: /
      initial_delay_seconds: 5
      period_seconds: 5
    depends_on:
      css-build:
        condition: process_completed_successfully

  css-build:
    command: npm run build

  css-watch:
    command: npm run css:watch
    depends_on:
      css-build:
        condition: process_completed_successfully
