version: "0.5"

processes:
  server:
    command: just server-watch
    readiness_probe:
      http_get:
        host: localhost
        port: ${PORT:-5150}
        path: /_health
      initial_delay_seconds: 5
      period_seconds: 10
    depends_on:
      css-build:
        condition: process_completed_successfully

  vendor-install:
    command: just vendor-install

  css-build:
    command: just css-build
    depends_on:
      vendor-install:
        condition: process_completed_successfully

  css-watch:
    command: just css-watch
    depends_on:
      css-build:
        condition: process_completed_successfully
